### ISSUE TITLE
Amending examples to communicate with nRF52 devices (using nRF5 SDK)

### ISSUE THREAD

**Issue by Gerriko** [pstolarz/nrfhal_arduino#1]
I have a nRF52840 device and am playing with the Nordic Semi nRF5 SDK. Within SDK are some examples (nRF Proprietary: https://infocenter.nordicsemi.com/topic/sdk_nrf5_v17.0.2/examples_esb.html) which should be able to be used to communicate with nRF24 devices (I'm using an Arduino with nRF24L01+ attached and using this library).

I am not sure if you've looked at this or tried this out before. 

I am struggling to work out the differences in settings within this library to get the two devices to talk to each other. 

For example, I know that these examples are configure with HAL_NRF_1MBPS where the nRF5 examples are using the 2MBPS setting. This is easily fixed. What is less clear is the addresses (one appears to be 5 bytes and the other is 4 bytes), one uses dynamic payload size and the other does not etc. etc. The part that has be really confused is that in the nRF5 examples they use: uint8_t addr_prefix[8] = {0xE7, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8 }; It's not clear if this is needed in Arduino sketch.

Maybe you have some tips or more advanced examples that have not been published. Thanks.

**Comment by pstolarz** [comment]
I'm afraid nRF52840 doesn't support ESB (proprietary Nordic wireless protocol) and you wont be able to use it to communicate with nRF24L01. As far as I know Nordic discontinued work on nRF24Lxx chips along with ESB used by the chip. New branch of their products work purely on industry standard protocols like BLE, Thread, ANT etc.

**Comment by pstolarz** [comment]
Back to your questions related to pipes. You should carefully read this [page](http://developer.nordicsemi.com/nRF51_SDK/nRF51_SDK_v4.x.x/doc/html/group__esb__users__guide.html). Especially **Pipes and addressing** section. The nRF5 SDK API allows to set base address (4 MSB bytes) of pipe 0 and 1 by `nrf_esb_set_base_address_0()` and `nrf_esb_set_base_address_1()`, and then set prefix to it (1 LSB byte) for 8 pipes respectively by `nrf_esb_set_prefixes()`. ESB supports up to 8 pipes while NRH_HAL only 6 (as specified in [nRF24L01 spec](https://www.sparkfun.com/datasheets/Components/SMD/nRF24L01Pluss_Preliminary_Product_Specification_v1_0.pdf)). Pipes 1-7 shares the same base of their address. So basing on the Nordic `esb_ptx/main.c` example
```c
    uint8_t base_addr_0[4] = {0xE7, 0xE7, 0xE7, 0xE7};
    uint8_t base_addr_1[4] = {0xC2, 0xC2, 0xC2, 0xC2};
    uint8_t addr_prefix[8] = {0xE7, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8 };
```
is equivalent to the following pipe addresses:
```
    0xE7, 0xE7, 0xE7, 0xE7, 0xE7 -> pipe0
    0xC2, 0xC2, 0xC2, 0xC2, 0xC2 -> pipe1
    0xC2, 0xC2, 0xC2, 0xC2, 0xC3 -> pipe2
    0xC2, 0xC2, 0xC2, 0xC2, 0xC4 -> pipe3
    0xC2, 0xC2, 0xC2, 0xC2, 0xC5 -> pipe4
    0xC2, 0xC2, 0xC2, 0xC2, 0xC6 -> pipe5
    0xC2, 0xC2, 0xC2, 0xC2, 0xC7 -> pipe6
    0xC2, 0xC2, 0xC2, 0xC2, 0xC8 -> pipe7
```
EDIT:
Also look at **Backwards Compatibility** section of the link mentioned above. It provides info related to communication between the nRF5 SDK ESB examples (for nRF51 chips) and legacy nRFgo SDK my lib bases on (nRF24L01 chips).

Hope it helps.

**Comment by Gerriko** [comment]
Thanks for that link and the explanation. That really helps. 
I know when I get the nRF52840 to use the Enhanced ShockBurst (ESB) TX example I can see multiple channels being used when I use the Arduino nRF24 scan example. Hopefully now with this added insight I can get the Arduino+nRF24L01+ to read the data.
